import { Router } from 'express';
import * as c from '../controllers/chef.controller.js';
import * as o from '../controllers/order.controller.js';
import * as rv from '../controllers/review.controller.js';
import { authenticate } from '../middleware/auth.js';
import { authorize } from '../middleware/rbac.js';
import { ROLES } from '../config/constants.js';
const r = Router();
r.post('/apply', authenticate, c.applyAsChef);
r.use(authenticate, authorize(ROLES.CHEF));
r.get('/me', c.myChefProfile);
r.patch('/me', c.updateMyChefProfile);
r.get('/dashboard', c.chefDashboard);
r.get('/dishes', c.myDishes);
r.post('/dishes', c.createDish);
r.patch('/dishes/:id', c.updateDish);
r.delete('/dishes/:id', c.deleteDish);
r.patch('/dishes/:id/toggle', c.toggleDish);
r.get('/orders', o.chefOrders);
r.patch('/orders/:id/status', o.chefUpdateStatus);
r.get('/settlements', c.myChefSettlements);
r.post('/reviews/:id/reply', rv.replyToReview);
export default r;
