import { Router } from 'express';
import * as c from '../controllers/customer.controller.js';
import { authenticate } from '../middleware/auth.js';
const r = Router();
r.use(authenticate);
r.get('/profile', c.myProfile);
r.get('/addresses', c.listAddresses);
r.post('/addresses', c.addAddress);
r.patch('/addresses/:id', c.updateAddress);
r.delete('/addresses/:id', c.deleteAddress);
r.get('/notifications', c.listNotifications);
r.patch('/notifications/:id/read', c.markNotificationRead);
r.patch('/notifications/read-all', c.markAllRead);
r.post('/fcm-token', c.registerFcmToken);
r.get('/coupons/:code', c.validateCoupon);
r.post('/subscriptions', c.createSubscription);
r.get('/subscriptions', c.mySubscriptions);
r.patch('/subscriptions/:id/pause', c.pauseSubscription);
r.patch('/subscriptions/:id/resume', c.resumeSubscription);
r.post('/catering', c.requestCatering);
r.get('/catering', c.myCatering);
export default r;
