import { Router } from 'express';
import authRoutes from './auth.routes.js';
import catalogRoutes from './catalog.routes.js';
import chefRoutes from './chef.routes.js';
import orderRoutes from './order.routes.js';
import deliveryRoutes from './delivery.routes.js';
import reviewRoutes from './review.routes.js';
import customerRoutes from './customer.routes.js';
import adminRoutes from './admin.routes.js';
import uploadRoutes from './upload.routes.js';

const router = Router();
router.use('/auth', authRoutes);
router.use('/catalog', catalogRoutes);
router.use('/chefs', chefRoutes);
router.use('/orders', orderRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/reviews', reviewRoutes);
router.use('/me', customerRoutes);
router.use('/admin', adminRoutes);
router.use('/uploads', uploadRoutes);
export default router;
